require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const connectDB = require('./config/db');
const User = require('./models/user');
const Policy = require('./models/policy');
const Scheme = require('./models/scheme');
const EligibilityRule = require('./models/eligibilityRule');
const Notification = require('./models/notification');
const { policies: policyPayloads, schemes: schemePayloads } = require('./seed-data-payloads');

const seed = async () => {
  await connectDB();
  console.log('Clearing existing data...');
  await Promise.all([
    User.deleteMany({}),
    Policy.deleteMany({}),
    Scheme.deleteMany({}),
    EligibilityRule.deleteMany({}),
    Notification.deleteMany({}),
  ]);

  const password = await bcrypt.hash('Password123', 10);

  const admin = await User.create({
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@policygpt.gov.in',
    password,
    role: 'Administrator',
  });

  const official = await User.create({
    firstName: 'Govt',
    lastName: 'Official',
    email: 'official@policygpt.gov.in',
    password,
    role: 'Government Official',
    organization: 'Ministry of Health',
  });

  const citizen = await User.create({
    firstName: 'Rahul',
    lastName: 'Sharma',
    email: 'citizen@example.com',
    password,
    role: 'Citizen',
    phone: '9876543210',
  });

  const policies = await Policy.insertMany([
    {
      title: 'Ayushman Bharat PM-JAY',
      summary: 'Health cover of ₹5 lakh per family per year for secondary and tertiary hospitalisation.',
      content: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana provides cashless treatment at empanelled hospitals across India for eligible families identified under SECC 2011.',
      category: 'Healthcare',
      ministry: 'Ministry of Health & Family Welfare',
      department: 'National Health Authority',
      state: 'All India',
      status: 'Active',
      tags: ['Healthcare', 'Insurance', 'BPL Families'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2018-09-23'),
    },
    {
      title: 'National Education Policy 2020',
      summary: 'Comprehensive framework for education transformation from school to higher education.',
      content: 'NEP 2020 replaces the previous National Policy on Education, 1986. It aims to universalize education from pre-school to secondary level with 100% GER by 2030.',
      category: 'Education',
      ministry: 'Ministry of Education',
      department: 'Department of School Education',
      state: 'All India',
      status: 'Active',
      tags: ['Education', 'Reform', 'Students'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2020-07-29'),
    },
    {
      title: 'Digital India Initiative',
      summary: 'Transform India into a digitally empowered society and knowledge economy.',
      content: 'Digital India aims to ensure government services are made available to citizens electronically by improving online infrastructure and increasing Internet connectivity.',
      category: 'Digital Governance',
      ministry: 'Ministry of Electronics & IT',
      department: 'MeitY',
      state: 'All India',
      status: 'Active',
      tags: ['Digital', 'Governance', 'Technology'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2015-07-01'),
    },
    {
      title: 'Pradhan Mantri Fasal Bima Yojana',
      summary: 'Crop insurance support for farmers to cover losses from natural calamities, pests, and diseases.',
      content: 'PMFBY provides risk coverage from pre-sowing to post-harvest with low premiums and direct claim payment for crop loss. It is designed to protect farmers from climate shocks and encourage cultivation of high-yield crops.',
      category: 'Agriculture',
      ministry: 'Ministry of Agriculture & Farmers Welfare',
      department: 'Department of Agriculture',
      state: 'All India',
      status: 'Active',
      tags: ['Agriculture', 'Insurance', 'Farmers'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2016-02-18'),
    },
    {
      title: 'PM Awas Yojana — Gramin',
      summary: 'Affordable pucca housing for rural BPL households with financial and technical support.',
      content: 'PMAY-G provides financial assistance for construction of permanent houses to eligible rural families, linked with MGNREGS support and geo-tagged monitoring. It aims to provide dignified housing across villages.',
      category: 'Housing',
      ministry: 'Ministry of Rural Development',
      department: 'Department of Rural Development',
      state: 'All India',
      status: 'Active',
      tags: ['Housing', 'Rural', 'BPL'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2016-11-20'),
    },
    {
      title: 'National Policy for Women Empowerment',
      summary: 'Framework to advance women’s development, rights, and participation across sectors.',
      content: 'This policy focuses on gender equality through education, health, economic empowerment, legal rights, and safety. It supports SHGs, financial inclusion, and community action against violence.',
      category: 'Women & Child Welfare',
      ministry: 'Ministry of Women and Child Development',
      department: 'Department of Women Empowerment',
      state: 'All India',
      status: 'Active',
      tags: ['Women', 'Empowerment', 'Gender'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2022-03-08'),
    },
    {
      title: 'National Employment Policy 2025',
      summary: 'A strategy to generate 10 crore jobs through skilling, MSME growth, and labour reform.',
      content: 'The policy outlines support for skill development, formalization of informal labour, employer incentives, and targeted employment in sunrise sectors such as green energy and digital services.',
      category: 'Employment',
      ministry: 'Ministry of Labour and Employment',
      department: 'Directorate General of Employment',
      state: 'All India',
      status: 'Active',
      tags: ['Employment', 'Jobs', 'MSME'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2025-01-15'),
    },
    {
      title: 'National Green Hydrogen Mission',
      summary: 'A plan to make India a global green hydrogen producer and exporter by 2030.',
      content: 'This mission targets 5 MMT of green hydrogen annual production, incentives for electrolyzer manufacturing, and industry decarbonization in steel, chemicals, and shipping.',
      category: 'Environment',
      ministry: 'Ministry of New and Renewable Energy',
      department: 'Department of New and Renewable Energy',
      state: 'All India',
      status: 'Active',
      tags: ['Environment', 'Energy', 'Hydrogen'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2023-01-04'),
    },
    {
      title: 'National Broadband Mission',
      summary: 'Connect all gram panchayats with high-speed broadband by 2025.',
      content: 'The mission expands BharatNet, supports last-mile connectivity, and lowers broadband costs so rural and urban areas can access digital services reliably.',
      category: 'Digital Governance',
      ministry: 'Ministry of Communications',
      department: 'Department of Telecommunications',
      state: 'All India',
      status: 'Active',
      tags: ['Digital', 'Broadband', 'Connectivity'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2019-12-17'),
    },
    {
      title: 'Atal Pension Yojana',
      summary: 'Guaranteed pension for informal sector workers after age 60.',
      content: 'APY offers monthly pensions from ₹1,000 to ₹5,000 based on contribution levels, with government co-contribution for eligible subscribers.',
      category: 'Finance',
      ministry: 'Ministry of Finance',
      department: 'Pension Fund Regulatory and Development Authority',
      state: 'All India',
      status: 'Active',
      tags: ['Finance', 'Pension', 'Retirement'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2015-06-01'),
    },
    {
      title: 'Bharatmala Pariyojana',
      summary: 'National highways and freight corridor development to improve transport efficiency.',
      content: 'Bharatmala focuses on bridge construction, highway expansion, logistics parks, and road network modernization to lower freight costs and connect economic corridors.',
      category: 'Infrastructure',
      ministry: 'Ministry of Road Transport and Highways',
      department: 'Department of Road Transport and Highways',
      state: 'All India',
      status: 'Active',
      tags: ['Infrastructure', 'Transport', 'Roads'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2017-05-01'),
    },
    {
      title: 'Smart Cities Mission',
      summary: 'Develop 100 smart cities with modern urban infrastructure and digital services.',
      content: 'The mission upgrades urban utilities, mobility, waste management, and citizen services through IoT and digital governance solutions.',
      category: 'Infrastructure',
      ministry: 'Ministry of Housing and Urban Affairs',
      department: 'Urban Affairs',
      state: 'All India',
      status: 'Active',
      tags: ['Smart City', 'Urban', 'Infrastructure'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2015-06-25'),
    },
    {
      title: 'National Nutrition Mission',
      summary: 'Improve child and maternal nutrition through targeted interventions and community outreach.',
      content: 'The mission promotes balanced diets, breastfeeding, supplementary nutrition, and health monitoring to reduce stunting, wasting, and anemia among children and mothers.',
      category: 'Healthcare',
      ministry: 'Ministry of Health & Family Welfare',
      department: 'Department of Health and Family Welfare',
      state: 'All India',
      status: 'Active',
      tags: ['Healthcare', 'Nutrition', 'Child Health'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2018-03-08'),
    },
    {
      title: 'Rashtriya Krishi Vikas Yojana',
      summary: 'Agricultural development through state-specific investments, infrastructure and decentralised planning.',
      content: 'RKVY empowers states to strengthen farm productivity, irrigation, market linkages, and farmer incomes by funding local crop and livestock initiatives.',
      category: 'Agriculture',
      ministry: 'Ministry of Agriculture & Farmers Welfare',
      department: 'Department of Agriculture',
      state: 'All India',
      status: 'Active',
      tags: ['Agriculture', 'Farmers', 'Infrastructure'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2018-02-01'),
    },
    {
      title: 'National Rural Livelihood Mission',
      summary: 'Enable sustainable livelihood generation for rural poor through SHGs and financial services.',
      content: 'NRLM mobilizes rural women into self-help groups, provides training, credit access, and market linkages to increase household incomes and economic resilience.',
      category: 'Employment',
      ministry: 'Ministry of Rural Development',
      department: 'Department of Rural Development',
      state: 'All India',
      status: 'Active',
      tags: ['Employment', 'Rural', 'Women'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2011-06-03'),
    },
    {
      title: 'National Clean Air Programme',
      summary: 'Reduce air pollution in key cities through source-based interventions and monitoring.',
      content: 'NCAP sets city-specific targets for particulate matter reduction, promotes clean fuels, and supports pollution monitoring networks and public awareness campaigns.',
      category: 'Environment',
      ministry: 'Ministry of Environment, Forest and Climate Change',
      department: 'Department of Environment, Forest and Climate Change',
      state: 'All India',
      status: 'Active',
      tags: ['Environment', 'Air Quality', 'Health'],
      author: official._id,
      approvedBy: admin._id,
      publishedAt: new Date('2019-01-10'),
    },
  ]);

  const schemes = await Scheme.insertMany([
    {
      name: 'PM Kisan Samman Nidhi',
      summary: 'Income support of ₹6,000 per year to all landholding farmer families.',
      details: 'PM-KISAN provides financial assistance in three equal installments of ₹2,000 every four months directly into beneficiaries bank accounts.',
      category: 'Farmer Welfare',
      ministry: 'Ministry of Agriculture & Farmers Welfare',
      department: 'Department of Agriculture',
      state: 'All India',
      eligibilityCriteria: ['All landholding farmer families', 'Cultivable land in their name', 'Not institutional landholders or income tax payers'],
      benefits: ['₹6,000 per year in 3 installments', 'Direct Benefit Transfer', 'No middlemen'],
      applicationMode: 'Online / PM Kisan Portal',
      launchDate: new Date('2019-02-24'),
      status: 'Active',
      tags: ['Farmer', 'Agriculture', 'Income Support'],
      author: official._id,
      approvedBy: admin._id,
    },
    {
      name: 'Ayushman Bharat PM-JAY',
      summary: 'Health insurance cover up to ₹5 lakh per family per year.',
      details: 'Covers secondary and tertiary care hospitalisation for over 10 crore poor and vulnerable families at empanelled hospitals.',
      category: 'Healthcare',
      ministry: 'Ministry of Health & Family Welfare',
      department: 'National Health Authority',
      state: 'All India',
      eligibilityCriteria: ['Families in SECC 2011 database', 'Deprived and occupational criteria families', 'No premium payment required'],
      benefits: ['₹5 lakh annual cover', 'Cashless treatment', '1,929 treatment packages'],
      applicationMode: 'Online / Hospital / CSC',
      launchDate: new Date('2018-09-23'),
      status: 'Active',
      tags: ['Healthcare', 'Insurance'],
      author: official._id,
      approvedBy: admin._id,
    },
    {
      name: 'PM Awas Yojana — Urban',
      summary: 'Housing for All in urban areas with credit-linked subsidy.',
      details: 'Provides affordable housing to urban poor including EWS, LIG and MIG categories with interest subsidy on home loans.',
      category: 'Housing',
      ministry: 'Ministry of Housing & Urban Affairs',
      department: 'HUA',
      state: 'All India',
      eligibilityCriteria: ['EWS/LIG/MIG categories', 'No pucca house in name', 'Annual income below ₹18 lakh'],
      benefits: ['Up to ₹2.67 lakh subsidy', 'Affordable housing', 'Credit-linked subsidy'],
      applicationMode: 'Online / CSC',
      launchDate: new Date('2015-06-25'),
      status: 'Active',
      tags: ['Housing', 'Urban', 'Subsidy'],
      author: official._id,
      approvedBy: admin._id,
    },
    {
      name: 'National Scholarship Portal',
      summary: 'One-stop platform for various government scholarship schemes for students.',
      details: 'Centralized portal for pre-matric, post-matric and merit-cum-means scholarships for SC, ST, OBC and minority students.',
      category: 'Scholarships',
      ministry: 'Ministry of Education',
      department: 'Department of Higher Education',
      state: 'All India',
      eligibilityCriteria: ['Indian students', 'Enrolled in recognized institutions', 'Category and income criteria vary by scheme'],
      benefits: ['Up to ₹12,000/year scholarship', 'Direct bank transfer', 'Multiple scheme options'],
      applicationMode: 'Online / scholarships.gov.in',
      launchDate: new Date('2015-08-01'),
      status: 'Active',
      tags: ['Education', 'Scholarship', 'Students'],
      author: official._id,
      approvedBy: admin._id,
    },
    {
      name: 'Stand Up India',
      summary: 'Bank loans between ₹10 lakh and ₹1 crore for SC/ST and women entrepreneurs.',
      details: 'Facilitates bank loans for greenfield enterprises in manufacturing, services or trading sectors by SC/ST and women borrowers.',
      category: 'Business Support',
      ministry: 'Ministry of Finance',
      department: 'Department of Financial Services',
      state: 'All India',
      eligibilityCriteria: ['SC/ST or Women entrepreneur', 'Above 18 years', 'Greenfield enterprise only'],
      benefits: ['₹10L - ₹1Cr loan', 'Composite loan', 'Handholding support'],
      applicationMode: 'Online / Bank Branch',
      launchDate: new Date('2016-04-05'),
      status: 'Draft',
      tags: ['Business', 'Entrepreneurship', 'Women'],
      author: official._id,
    },
    {
      name: 'MGNREGA',
      summary: '100 days of guaranteed wage employment in a financial year for rural households.',
      details: 'Mahatma Gandhi National Rural Employment Guarantee Act provides legal guarantee for at least 100 days of wage employment.',
      category: 'Employment Programs',
      ministry: 'Ministry of Rural Development',
      department: 'Department of Rural Development',
      state: 'All India',
      eligibilityCriteria: ['Adult members of rural households', 'Willing to do unskilled manual work', 'Job card registration required'],
      benefits: ['100 days guaranteed work', 'Minimum wage payment', 'Asset creation in villages'],
      applicationMode: 'Gram Panchayat / Online',
      launchDate: new Date('2006-02-02'),
      status: 'Active',
      tags: ['Employment', 'Rural', 'Wages'],
      author: official._id,
      approvedBy: admin._id,
    },
  ]);

  await EligibilityRule.insertMany([
    {
      scheme: schemes[0]._id,
      ageRange: { min: 18, max: 100 },
      gender: 'Any',
      incomeLimit: 'Any',
      occupation: 'Farmer',
      education: 'Any',
      location: 'Any',
      socialCategory: 'Any',
      disabilityStatus: 'Any',
    },
    {
      scheme: schemes[1]._id,
      ageRange: { min: 0, max: 100 },
      gender: 'Any',
      incomeLimit: '250000',
      occupation: 'Any',
      education: 'Any',
      location: 'Any',
      socialCategory: 'Any',
      disabilityStatus: 'Any',
    },
    {
      scheme: schemes[2]._id,
      ageRange: { min: 18, max: 70 },
      gender: 'Any',
      incomeLimit: '300000',
      occupation: 'Any',
      education: 'Any',
      location: 'Any',
      socialCategory: 'Any',
      disabilityStatus: 'Any',
    },
    {
      scheme: schemes[3]._id,
      ageRange: { min: 5, max: 30 },
      gender: 'Any',
      incomeLimit: '250000',
      occupation: 'Student',
      education: '10th Pass',
      location: 'Any',
      socialCategory: 'Any',
      disabilityStatus: 'Any',
    },
    {
      scheme: schemes[5]._id,
      ageRange: { min: 18, max: 65 },
      gender: 'Any',
      incomeLimit: 'Any',
      occupation: 'Any',
      education: 'Any',
      location: 'Rural',
      socialCategory: 'Any',
      disabilityStatus: 'Any',
    },
  ]);

  await Notification.insertMany([
    {
      title: 'PM Kisan Installment Due',
      message: 'Next PM Kisan installment will be credited in 5 days. Ensure your bank details are updated.',
      type: 'warning',
      category: 'Scheme Update',
      targetRoles: ['Citizen'],
    },
    {
      title: 'New Healthcare Policies Added',
      message: '3 new health policies have been published on the platform.',
      type: 'success',
      category: 'New Policy',
      targetRoles: ['Citizen', 'Researcher'],
    },
    {
      title: 'NSP Application Deadline',
      message: 'National Scholarship Portal applications close tonight at 11:59 PM.',
      type: 'danger',
      category: 'Deadline',
      targetRoles: ['Citizen'],
    },
    {
      title: 'Policy Review Required',
      message: 'Solar Rooftop Scheme is pending approval.',
      type: 'info',
      category: 'Policy Update',
      targetRoles: ['Administrator', 'Government Official'],
    },
  ]);

  console.log('Seed completed successfully!');
  console.log('Test accounts (password: Password123):');
  console.log('  Admin:    admin@policygpt.gov.in');
  console.log('  Official: official@policygpt.gov.in');
  console.log('  Citizen:  citizen@example.com');
  console.log(`  Policies: ${policies.length}, Schemes: ${schemes.length}`);

  await mongoose.connection.close();
  process.exit(0);
};

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
